# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestApplication.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import can

class Ui_OBJ(object):
    def setupUi(self, OBJ):
        OBJ.setObjectName("OBJ")
        OBJ.resize(614, 590)
        OBJ.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        OBJ.setAccessibleName("")
        self.groupBox = QtWidgets.QGroupBox(OBJ)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 571, 371))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 501, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 80, 141, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setProperty("intValue", 80)
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 210, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(130, 120, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(300, 120, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(20, 230, 131, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 170, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(340, -30, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_2.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(340, 160, 131, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 100, 131, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 220, 131, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 231, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 101, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 20, 221, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 40, 171, 61))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 220, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(270, 220, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 141, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(280, 190, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(160, 250, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(400, 250, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(270, 250, 55, 16))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton1_GDN = QtWidgets.QPushButton(self.tab_3)
        self.pushButton1_GDN.setGeometry(QtCore.QRect(230, 180, 181, 41))
        self.pushButton1_GDN.setObjectName("pushButton1_GDN")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(120, 80, 321, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_byte_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_8.setGeometry(QtCore.QRect(280, 40, 21, 31))
        self.lineEdit_byte_8.setObjectName("lineEdit_byte_8")
        self.lineEdit_byte_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_6.setGeometry(QtCore.QRect(206, 39, 21, 31))
        self.lineEdit_byte_6.setObjectName("lineEdit_byte_6")
        self.lineEdit_byte_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_2.setGeometry(QtCore.QRect(55, 38, 21, 31))
        self.lineEdit_byte_2.setObjectName("lineEdit_byte_2")
        self.lineEdit_byte_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_3.setGeometry(QtCore.QRect(93, 38, 21, 31))
        self.lineEdit_byte_3.setObjectName("lineEdit_byte_3")
        self.lineEdit_byte_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_5.setGeometry(QtCore.QRect(169, 38, 21, 31))
        self.lineEdit_byte_5.setObjectName("lineEdit_byte_5")
        self.lineEdit_byte1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte1.setGeometry(QtCore.QRect(19, 37, 21, 31))
        self.lineEdit_byte1.setObjectName("lineEdit_byte1")
        self.lineEdit_byte_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_4.setGeometry(QtCore.QRect(130, 37, 21, 31))
        self.lineEdit_byte_4.setObjectName("lineEdit_byte_4")
        self.lineEdit_byte_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_byte_7.setGeometry(QtCore.QRect(243, 40, 21, 31))
        self.lineEdit_byte_7.setObjectName("lineEdit_byte_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(24, 18, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(64, 19, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(103, 20, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(142, 21, 31, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(176, 21, 31, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(211, 21, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(249, 22, 31, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(287, 23, 31, 16))
        self.label_20.setObjectName("label_20")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 80, 91, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_byte_ID = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_byte_ID.setGeometry(QtCore.QRect(20, 32, 41, 30))
        self.lineEdit_byte_ID.setObjectName("lineEdit_byte_ID")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_2 = QtWidgets.QGroupBox(OBJ)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 380, 571, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(OBJ)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 520, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(OBJ)
        self.textEdit.setGeometry(QtCore.QRect(120, 520, 411, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(OBJ)
        self.label.setGeometry(QtCore.QRect(20, 560, 511, 16))
        self.label.setObjectName("label")

        self.retranslateUi(OBJ)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OBJ)

    def retranslateUi(self, OBJ):
        _translate = QtCore.QCoreApplication.translate
        OBJ.setWindowTitle(_translate("OBJ", "3P-001 Simulator Application        Version1.0"))
        self.groupBox.setTitle(_translate("OBJ", "Select Subsystem"))
        self.pushButton_4.setText(_translate("OBJ", "Start Therapy"))
        self.label_9.setText(_translate("OBJ", "PPM"))
        self.label_10.setText(_translate("OBJ", "Gas filter"))
        self.label_11.setText(_translate("OBJ", "Battery "))
        self.pushButton_5.setText(_translate("OBJ", "Alarm History"))
        self.pushButton_6.setText(_translate("OBJ", "Patient"))
        self.pushButton_7.setText(_translate("OBJ", "Firmware Upgrade"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OBJ", " UCM"))
        self.groupBox_3.setTitle(_translate("OBJ", "Switches"))
        self.checkBox.setText(_translate("OBJ", "Main ON/OFF"))
        self.checkBox_2.setText(_translate("OBJ", "Door Open"))
        self.groupBox_5.setTitle(_translate("OBJ", "Bezel LEDs"))
        self.pushButton_3.setText(_translate("OBJ", "GREEN"))
        self.label_2.setText(_translate("OBJ", "Charge level   BATT-1"))
        self.label_3.setText(_translate("OBJ", "Charge level   BATT-2"))
        self.label_4.setText(_translate("OBJ", "0%"))
        self.label_5.setText(_translate("OBJ", "100%"))
        self.label_6.setText(_translate("OBJ", "100%"))
        self.label_7.setText(_translate("OBJ", "0%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OBJ", "PCW"))
        self.pushButton1_GDN.setText(_translate("OBJ", "Send CAN Message"))

        self.pushButton1_GDN.clicked.connect(self.clickMethod)

        self.groupBox_4.setTitle(_translate("OBJ", "Data Bytes"))
        self.lineEdit_byte_8.setText(_translate("OBJ", "5"))
        self.lineEdit_byte_6.setText(_translate("OBJ", "5"))
        self.lineEdit_byte_2.setText(_translate("OBJ", "1"))
        self.lineEdit_byte_3.setText(_translate("OBJ", "2"))
        self.lineEdit_byte_5.setText(_translate("OBJ", "2"))
        self.lineEdit_byte1.setText(_translate("OBJ", "3"))
        self.lineEdit_byte_4.setText(_translate("OBJ", "2"))
        self.lineEdit_byte_7.setText(_translate("OBJ", "5"))
        self.label_13.setText(_translate("OBJ", "1"))
        self.label_14.setText(_translate("OBJ", "2"))
        self.label_15.setText(_translate("OBJ", "3"))
        self.label_16.setText(_translate("OBJ", "4"))
        self.label_17.setText(_translate("OBJ", "5"))
        self.label_18.setText(_translate("OBJ", "6"))
        self.label_19.setText(_translate("OBJ", "7"))
        self.label_20.setText(_translate("OBJ", "8"))
        self.groupBox_6.setTitle(_translate("OBJ", "Identifier"))
        self.lineEdit_byte_ID.setText(_translate("OBJ", "7FF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OBJ", "GDN"))
        self.groupBox_2.setTitle(_translate("OBJ", "Monitor Subsystem  messages"))
        self.pushButton_2.setText(_translate("OBJ", "Select Log"))
        self.textEdit.setHtml(_translate("OBJ", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">C:\\Users\\Rohith Sasidharan\\Documents\\CANMessagesLog.txt</span></p></body></html>"))
        self.label.setText(_translate("OBJ", "STATUS:  Node disconnected from CAN bus"))

    def clickMethod(self):
         byte1 = int(self.lineEdit_byte1.text(), 16)
         byte2 = int(self.lineEdit_byte_2.text(), 16)
         byte3 = int(self.lineEdit_byte_3.text(), 16)
         byte4 = int(self.lineEdit_byte_4.text(), 16)
         byte5 = int(self.lineEdit_byte_5.text(), 16)
         byte6 = int(self.lineEdit_byte_6.text(), 16)
         byte7 = int(self.lineEdit_byte_7.text(), 16)
         byte8 = int(self.lineEdit_byte_8.text(), 16)
         self.ID = int(self.lineEdit_byte_ID.text(), 16)
       
         bus = can.interface.Bus(channel='can0', bustype='socketcan_native')
         msg = can.Message(arbitration_id=self.ID,data=[byte1,byte2,byte3,byte4,byte5,byte6,byte7,byte8],extended_id=False)
         bus.send(msg)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OBJ = QtWidgets.QDialog()
    ui = Ui_OBJ()
    ui.setupUi(OBJ)
    OBJ.show()
    sys.exit(app.exec_())
